### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by rymkapro** [ngnjs/libcrypto#2]
Hi!
Do you plan to add typescript typings for your great package?

**Comment by coreybutler** [comment]
We don't really use Typescript, so no, there isn't a plan to add typings. We recognize the importance of typings for many users though, so I'd accept a PR with a types file if someone wants to put it together.

Alternatively, the library is documented using JSDoc conventions. I'm not sure if the current convention is compatible with tsconfig (haven't tested it), but I don't think it would be too much effort to add tsconfig-compatible typings if the current doc conventions aren't sufficient. That would allow Typescript users to generate `.d.ts` files.

**Comment by rymkapro** [comment]
Thanks for your answer ;)
